### ISSUE TITLE
code problem when train my dataset

### ISSUE THREAD

**Issue by MrDec** [Linwei-Chen/Seg-Aliasing#5]
Traceback (most recent call last):
  File "train.py", line 243, in <module>
    main()
  File "train.py", line 215, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/dww/anaconda3/envs/seg/lib/python3.8/site-packages/mmseg/datasets/builder.py", line 85, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/dww/anaconda3/envs/seg/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'IRSTD1K is not in the dataset registry'

**Comment by MrDec** [comment]
I just python train.py "the path to config".   hope your reply

**Comment by Linwei-Chen** [comment]
Our code is based on mmseg. It seems that we need to add a new dataset using mmseg. You can find instructions on how to do this [here](https://mmsegmentation.readthedocs.io/en/main/advanced_guides/add_datasets.html).
